In [1]:
import pandas as pd

df = pd.read_csv("base.csv")
display(df)

,Player Name,Team-name,Age,Position,App,MinP,Goals,Assist,YC,RC,SPG,PS%,AW,MOTM,Rating
0,Robert Lewandowski,Barcelona,34,FW,20(1),1682,15.0,5.0,NaN,1.0,3.8,79,1.6,7.0,7.53
1,Karim Benzema,Real Madrid,35,FW,15,1306,11.0,3.0,1.0,NaN,4.7,87,0.7,4.0,7.45
2,Antoine Griezmann,Atletico,31,AM(CLR) FW,18(7),1693,8.0,8.0,NaN,NaN,2.6,81.5,0.8,5.0,7.45
3,Vinícius Júnior,Real Madrid,22,AM(L) FW,24,2122,8.0,4.0,8.0,NaN,2.5,82.3,NaN,4.0,7.38
4,Pedri,Barcelona,20,AM(CL),18(3),1634,6.0,NaN,2.0,NaN,0.8,88.5,NaN,3.0,7.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,Carlos Álvarez,Sevilla,19,Midfielder,0(1),9,NaN,NaN,1.0,NaN,NaN,100,NaN,NaN,5.89
538,Tomás Alarcón,Cadiz,24,DMC,2(2),222,NaN,NaN,NaN,1.0,0.5,84.3,0.8,NaN,5.82
539,Álvaro Giménez,Cadiz,31,FW,0(1),16,NaN,NaN,NaN,NaN,NaN,100,NaN,NaN,5.82
540,John Donald,Elche,22,D(C),2(1),151,NaN,NaN,NaN,1.0,NaN,87.5,0.7,NaN,5.71
541,Diego López,Rayo Vallecano,41,GK,1,90,NaN,NaN,NaN,NaN,NaN,70.8,NaN,NaN,4.63

In [18]:
df900 = df[df['MinP'] > 900]
d = df900.groupby('Team-name',as_index=False).agg(
    Total_Amarelos=('YC', 'sum'),
    Total_Vermelhos=('RC', 'sum')
)
display(d)

          Team-name  Total_Amarelos  Total_Vermelhos
0           Almeria            45.0              1.0
1   Athletic Bilbao            30.0              3.0
2          Atletico            44.0              6.0
3         Barcelona            42.0              5.0
4             Cadiz            42.0              5.0
5        Celta Vigo            43.0              2.0
6             Elche            44.0              4.0
7          Espanyol            41.0              5.0
8            Getafe            55.0              4.0
9            Girona            41.0              1.0
10         Mallorca            65.0              2.0
11          Osasuna            60.0              3.0
12   Rayo Vallecano            52.0              2.0
13       Real Betis            38.0             10.0
14      Real Madrid            36.0              1.0
15    Real Sociedad            44.0              2.0
16  Real Valladolid            42.0              3.0
17          Sevilla            48.0              6.0
18         Valencia            48.0              2.0
19       Villarreal            42.0              1.0

In [19]:
d["Total Car"] = d["Total_Amarelos"] + d["Total_Vermelhos"]
d = d.sort_values("Total Car", ascending=False)
display(d)

          Team-name  Total_Amarelos  Total_Vermelhos  Total Car
10         Mallorca            65.0              2.0       67.0
11          Osasuna            60.0              3.0       63.0
8            Getafe            55.0              4.0       59.0
12   Rayo Vallecano            52.0              2.0       54.0
17          Sevilla            48.0              6.0       54.0
2          Atletico            44.0              6.0       50.0
18         Valencia            48.0              2.0       50.0
6             Elche            44.0              4.0       48.0
13       Real Betis            38.0             10.0       48.0
3         Barcelona            42.0              5.0       47.0
4             Cadiz            42.0              5.0       47.0
15    Real Sociedad            44.0              2.0       46.0
0           Almeria            45.0              1.0       46.0
7          Espanyol            41.0              5.0       46.0
16  Real Valladolid            42.0              3.0       45.0
5        Celta Vigo            43.0              2.0       45.0
19       Villarreal            42.0              1.0       43.0
9            Girona            41.0              1.0       42.0
14      Real Madrid            36.0              1.0       37.0
1   Athletic Bilbao            30.0              3.0       33.0

In [20]:
d.to_excel("Cartao.xlsx", index=False)